title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: AIML Scientist and Professor by Profession, AI Ethicist and Poet by Passion
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
