title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: "<span style='color:blue;'>AIML Scientist, Professor and AI Ethicist</span> Marquis Who's Who 2024"
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
