---
layout: page
title: Ray Islam, PhD
theme: jekyll-theme-minimal
---

![Ray Islam, PhD](/assets/images/headshot.jpg)

<span style='color:blue;'>AIML Scientist, Professor and AI Ethicist Marquis Who's Who 2024</span>

![Logo](https://badges.marquiswhoswho.com/Badge/honoredlistee/7089e97a4c174658af349b92b651e91877716451078c49d59786967a7eba6bca)
