title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: A Scientist and a Professor (by Profession)
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
