title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: A Scientist and Professor by Profession, Researcher and Poet by Hobby
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
