title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: "<span style='color:blue;'>AI/ML Scientist | Professor | Published Author | AI Ethicist | <a href='https://www.24-7pressrelease.com/press-release/515473/dr-ray-islam-displays-excellence-in-education-and-technology' target='_blank' style='color:blue; text-decoration:none;'>Marquis Who's Who 2024</a></span>"
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
