title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
badge_url: https://badges.marquiswhoswho.com/Badge/honoredlistee/7089e97a4c174658af349b92b651e91877716451078c49d59786967a7eba6bca
description: "<span style='color:blue;'>AIML Scientist, Professor and AI Ethicist Marquis Who's Who 2024</span>"
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
