title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: "<span style='color:#006bb3;'><a href='https://www.24-7pressrelease.com/press-release/515473/dr-ray-islam-displays-excellence-in-education-and-technology' target='_blank' style='color:blue; text-decoration:none;'>AI/ML Scientist | Professor | Test | Published Author | AI Ethicist | Marquis Who's Who 2024-25</a></span>"
theme: jekyll-theme-minima
