title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: A Scientist and Professor by Profession
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#333"
description_size: "1.2em"
