title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: "<div style='text-align:center; color:blue; margin:0;'>AIML Scientist, Professor and AI Ethicist Marquis Who's Who 2024</div>"
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
