title: Ray Islam, PhD
headshot_logo: /assets/images/headshot.jpg
badge_logo: /assets/images/badge.png
description: "<span style='color:blue;'>AIML Scientist, Professor and AI Ethicist Marquis Who's Who 2024</span>"
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
