title: Ray Islam, PhD
logo1: /assets/images/headshot.jpg
description: "<span style='color:blue;'>AIML Scientist, Professor and AI Ethicist Marquis Who's Who 2024</span>"
logo2: /assets/images/Badge.jpg
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#000000"
description_size: "1.2em"
