title: Ray Islam, PhD
logo: /assets/images/headshot.jpg
description: A Scientist and Professor by Profession-3
theme: jekyll-theme-minimal
description_font: "Georgia, serif"
description_color: "#666"
description_size: "1.2em"
